version: "3.7"
services:

  nginx:
    #image: nginx:0.1
    image: 192.87.106.18:56001/nginx:0.1
    labels: 
      MY_DLO_ENVIRONMENT: development
      MY_DLO_PURPOSE: an portal service
    ports:
      # platform:56000+, dev:57000+, demo:58000+, pilot:59000+
      - $STACK_PORT:80
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
      restart_policy:
        condition: any
    networks:
      - $STACK_NETWORK
    volumes:
      #- $PWD/conf:/etc/nginx/conf.d
      #- $PWD/html:/usr/share/nginx/html
      #- $PWD/src/$STACK_SERVICE:/var/$STACK_SERVICE
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/conf:/etc/nginx/conf.d
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/html:/usr/share/nginx/html
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/src/$STACK_SERVICE:/var/$STACK_SERVICE

  php:
    #image: php-fpm:0.1
    image: 192.87.106.18:56001/php-fpm:0.2
    deploy:
      mode: replicated
      replicas: 1
#      resources:
#        limits:
#          cpus: '1.0'
#          memory: 256M
      restart_policy:
        condition: any
    secrets:
      - portal_db_dba_password
    environment:
      # app
      APP_ENV: ${STACK_ENV_MOD}
      APP_SECRET: "d0e0b906b0b783794908ed04e2a16cbf"
      # saml
      BASE_URL: $STACK_NETWORK_URL
      ENTITY_ID: ${STACK_NETWORK_URL_IDP}/saml2/idp/metadata.php
      SINGLE_SIGN_ON_SERVICE: ${STACK_NETWORK_URL_IDP}/saml2/idp/SSOService.php
      SINGLE_LOGOUT_SERVICE: ${STACK_NETWORK_URL_IDP}/saml2/idp/SingleLogoutService.php
      ENTITY_ID_SP: ${STACK_NETWORK_URL}/saml/metadata
      ASSERTION_CONSUMER_SERVICE_SP: ${STACK_NETWORK_URL}/saml/acs
      SINGLE_LOGOUT_SERVICE_SP: ${STACK_NETWORK_URL}/saml/logout
      IDP_CERT: ${STACK_NETWORK_IDP_FINGERPRINT}
      # attributes
      # - get uid from saml response
      # database
      DB_HOST: ${STACK_SERVICE}_db
      DB_USER: 'dba'
      DB_NAME: 'portal'
      DB_PASS_FILE: /run/secrets/portal_db_dba_password
      DB_PORT: 3306
      # startup
      PHP_STACK_SERVICE: $STACK_SERVICE
      PHP_DB: 'portal'
    networks:
      - $STACK_NETWORK
    volumes:
      #- $PWD/src/$STACK_SERVICE:/var/$STACK_SERVICE
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/src/$STACK_SERVICE:/var/$STACK_SERVICE
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/data:/var/data
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/tmp/startup1.sh:/startup.sh

  composer:
    #image: composer:0.1
    image: 192.87.106.18:56001/composer:0.1
    command: install
    deploy:
      mode: replicated
      replicas: 1
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 128M
      restart_policy:
        condition: none
    networks:
      - $STACK_NETWORK
    volumes:
      #- $PWD/src/$STACK_SERVICE:/app
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/src/$STACK_SERVICE:/app

  db:
    #image: mysql:5.7
    image: 192.87.106.18:56001/mysql:0.1
    configs:
      - source: portal_my_cnf
        target: /etc/mysql/conf.d/my.cnf
    secrets:
      - portal_db_root_password
      - portal_db_dba_password
#    deploy:
#      mode: replicated
#      replicas: 1
#      resources:
#        limits:
#          cpus: '1.0'
#          memory: 512M
#      restart_policy:
#        condition: any
#      placement:
#        constraints: [node.role == manager]
    environment:
      MYSQL_USER: dba
      MYSQL_DATABASE: portal
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/portal_db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/portal_db_dba_password
    networks:
      - $STACK_NETWORK
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- .data/mysql:/var/lib/mysql
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/data/mysql:/var/lib/mysql

  startup:
    #image: alpine:0.1
    image: 192.87.106.18:56001/alpine:0.1
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
      restart_policy:
        condition: none
    environment:
      PHP_STACK_SERVICE: $STACK_SERVICE
    networks:
      - $STACK_NETWORK
    volumes:
      #- $PWD/src/$STACK_SERVICE:/app
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION:/data
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/tmp/startup2.sh:/startup.sh

networks:
  dev-net:
    external: true
  test-net:
    external: true
  exp-net:
    external: true

secrets:
  portal_db_root_password:
    external: true
  portal_db_dba_password:
    external: true

configs:
  portal_my_cnf:
    external: true

