version: "3.7"
services:

  nginx:
    #image: nginx:0.1
    image: 192.87.106.18:56001/nginx:0.1
    labels: 
      MY_DLO_ENVIRONMENT: development
      MY_DLO_PURPOSE: an portal service
    ports:
      # platform:56000+, dev:57000+, demo:58000+, pilot:59000+
      - 57202:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - $STACK_NETWORK
    volumes:
      #- $PWD/conf:/etc/nginx/conf.d
      #- $PWD/html:/usr/share/nginx/html
      #- $PWD/src/$STACK_SERVICE:/var/$STACK_SERVICE
      #- /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE-$STACK_VERSION/conf:/etc/nginx/conf.d
      #- /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE-$STACK_VERSION/html:/usr/share/nginx/html
      #- /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE-$STACK_VERSION/src/$STACK_SERVICE:/var/$STACK_SERVICE
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/portal-0.1/conf:/etc/nginx/conf.d
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/portal-0.1/html:/usr/share/nginx/html
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/portal-0.1/src/$STACK_SERVICE:/var/$STACK_SERVICE

  php:
    #image: php-fpm:0.1
    image: 192.87.106.18:56001/php-fpm:0.2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    secrets:
      - portal_db_dba_password
    environment:
      # app
      APP_ENV: "dev"
      APP_SECRET: "d0e0b906b0b783794908ed04e2a16cbf"
      PORTAL_URL: "http://www.dlo.surfnet.nl"
      # saml
      BASE_URL: "http://portaal.dlo.surfnet.nl/"
      ENTITY_ID: "http://idp.dlo.surfnet.nl/saml2/idp/metadata.php"
      SINGLE_SIGN_ON_SERVICE: "http://idp.dlo.surfnet.nl/saml2/idp/SSOService.php"
      SINGLE_LOGOUT_SERVICE: "http://idp.dlo.surfnet.nl/saml2/idp/SingleLogoutService.php"
      ENTITY_ID_SP: "http://portaal.dlo.surfnet.nl/saml/metadata"
      ASSERTION_CONSUMER_SERVICE_SP: "http://portaal.dlo.surfnet.nl/saml/acs"
      SINGLE_LOGOUT_SERVICE_SP: "http://portaal.dlo.surfnet.nl/saml/logout"
      IDP_CERT: "00:B8:D9:22:1D:50:BE:DB:4D:1F:6E:B2:4B:66:59:BB:3B:D1:87:39"
      # attributes
      UID: "uid"
      GIVENNAME: "givenName"
      SN: "sn"
      EMAIL: "mail"
      #EPPN: "eduPersonPrincipalName"
      EPPN: "uid"
      # database
      DB_HOST: '192.87.106.21'
      DB_USER: 'dba'
      DB_NAME: 'portal'
      DB_PASS_FILE: /run/secrets/portal_db_dba_password
      DB_PORT: 3308
    networks:
      - $STACK_NETWORK
    volumes:
      #- $PWD/src/$STACK_SERVICE:/var/$STACK_SERVICE
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/portal-0.1/src/$STACK_SERVICE:/var/$STACK_SERVICE

  composer:
    #image: composer:0.1
    image: 192.87.106.18:56001/composer:0.1
    command: install
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    networks:
      - $STACK_NETWORK
    volumes:
      #- $PWD/src/$STACK_SERVICE:/app
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/portal-0.1/src/$STACK_SERVICE:/app

  db:
    #image: mysql:5.7
    image: 192.87.106.18:56001/mysql:0.1
    configs:
      - source: portal_my_cnf
        target: /etc/mysql/conf.d/my.cnf
    secrets:
      - portal_db_root_password
      - portal_db_dba_password
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    ports:
      - 3308:3306
    environment:
      MYSQL_USER: dba
      MYSQL_DATABASE: portal
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/portal_db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/portal_db_dba_password
    networks:
      - dev-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- .data/mysql:/var/lib/mysql
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/portal-0.1/data/mysql:/var/lib/mysql

networks:
  #$STACK_NETWORK:
  dev-net:
    external: true

secrets:
  portal_db_root_password:
    external: true
  portal_db_dba_password:
    external: true

configs:
  portal_my_cnf:
    external: true

